### ISSUE TITLE
Access database

### ISSUE THREAD

**Issue by vadim-ivlev** [govwiki/govwiki.us#1]
Marc, there is Access govwiki.accdb file in data/ folder. It would be great if you kept the data in that file. This way it will be very easy to export them to any format and upload data to an outer datastore.

**Comment by joffemd** [comment]
I can do this, but don't know which folder you are referring to.  I don't see it on Google Drive (which I suppose can't take Access files anyway).

**Comment by vadim-ivlev** [comment]
Sorry. I did not clarify. It's in this project. https://github.com/govwiki/govwiki.us/tree/gh-pages/data .

Here we write about issues of govwiki.us GitHub project.

**Comment by vadim-ivlev** [comment]
Now I am not sure. It might be a good idea to keep data on Google Drive.(?)

https://drive.google.com/drive/u/0/#folders/0B52vSh0ZfsISfnRqTURJbmwxc2U5S0RabFRqWlk1MmtZMFRRRzBmZDc5Smp6SkhYRnpNdlk/0B52vSh0ZfsISfkxtRk9tQUtlVG5pSkh4N1drYWFoNzd4clVUU251TV9YNEhUZmxpeERDNk0/0B52vSh0ZfsISflAtR2FQdVNiM2JqRkhTR1VHLVdmSS1TVHZIT3F5RlNxd2hWOUc3SEtnN0U

**Comment by joffemd** [comment]
Uploading the file now.  It is 600mb partially because I included some other data.  Some of this data will eventually be included on the site, but you can ignore it for now.

**Comment by joffemd** [comment]
Sorry.  I placed it on the Google Drive.  Will that be okay for now, or do you want me to move it here?

**Comment by vadim-ivlev** [comment]
I didn't think it's that much.) Is that possible to compact the file ?
Delete unnecessary tables? Zip it?  If not, we will have to keep data on a
cloud data server.

**Comment by joffemd** [comment]
I tried compacting it before uploading and did not get a shrinkage.  Zipping won’t make much difference.  I also really want to retain the extra tables I added.

If you don’t want to rely on the Google drive another option is to place the data on Azure.

**Comment by vadim-ivlev** [comment]
Marc, i have already zipped it. It's 3 times smaller now. ) Look in the
data/ folder on Google drive. )

**Comment by joffemd** [comment]
Yup.  I stand corrected!
