### ISSUE TITLE
Make ZIP and GOV_TYPE searchable by search field

### ISSUE THREAD

**Issue by vadim-ivlev** [govwiki/govwiki.us#6]

**Comment by vadim-ivlev** [comment]
done.

**Comment by joffemd** [comment]
How does Marc see Vadim's recent changes?

**Comment by joffemd** [comment]
Place the area map for each government in a tab.  Right now, it is using screen real estate that will ne needed for textual data.

**Comment by vadim-ivlev** [comment]
The map placement should be a different issue: Layout, I guess.
As to this one. Now the user can  type  gov name AND state AND gov type in the search field.

**Comment by joffemd** [comment]
Ok I see.  This is clever but I think users would find it confusing.  I suggest a filter button which shows a popup.  The popup would allow the user to select a state and government type.  These selections would then limit the options available when typing into the autocomplete text box.
