### ISSUE TITLE
Need advice on editing MongoDB collections

### ISSUE THREAD

**Issue by joffemd** [govwiki/govwiki.us#9]
MongoVue looks pretty limited.  Is there some tool with a spreadsheet-style interface that allows calues to be changed and columns to be added?

**Comment by vadim-ivlev** [comment]
http://docs.mongodb.org/ecosystem/tools/administration-interfaces/

**Comment by vadim-ivlev** [comment]
I like 

http://3t.io/mongochef/

It;s free for non commercial use. 
It allows edit records in grid form.
Insert new columns build queries. etc.

**Comment by joffemd** [comment]
I tried it.  I like the fact that I can edit data in a spreadsheet format, but copying and pasting capabilities are limited.

**Comment by vadim-ivlev** [comment]
Have you tried right mouse button?

**Comment by joffemd** [comment]
I see that it has a “Copy” function, but it just copies a whole JSON structure.  This is not useful when pasting to Excel, where I need to see the data laid out into discrete rows and columns.

**Comment by vadim-ivlev** [comment]
You can try to export to csv and open it in excel.

**Comment by vadim-ivlev** [comment]
Mongo is command line thing like MySQl. 
May be we need something like MongoDB ODBC driver?
http://www.rssbus.com/odbc/mongodb/

**Comment by vadim-ivlev** [comment]
The driver looks good in Access

**Comment by vadim-ivlev** [comment]
you can 
![4](https://cloud.githubusercontent.com/assets/3027648/6694126/f9c38878-cce8-11e4-9570-30e3116b1654.PNG)
make queries

![5](https://cloud.githubusercontent.com/assets/3027648/6694130/037e547e-cce9-11e4-9399-37616647c17d.PNG)

**Comment by vadim-ivlev** [comment]
Here is supported sql

http://cdn.rssbus.com/help/DG1/odbc/pg_overview.htm

**Comment by vadim-ivlev** [comment]
http://www.querymongo.com/
